//注册的jquery方法
var jqdatas = [{
        title: "属性操作",
        props: [{
            val: "attr",
            //是在fn上的方法
            fn: 1
        }, {
            val: "removeAttr",
            fn: 1
        }, {
            val: "prop",
            fn: 1
        }, {
            val: "removeProp",
            fn: 1
        }, {
            val: "addClass",
            fn: 1
        }, {
            val: "removeClass",
            fn: 1
        }, {
            val: "toggleClass",
            fn: 1
        }, {
            val: "html",
            fn: 1
        }, {
            val: "text",
            fn: 1
        }, {
            val: "val",
            fn: 1
        }]
    }, {
        title: "CSS相关和定位",
        props: [{
            val: "css",
            fn: 1
        }, {
            val: "offset",
            fn: 1
        }, {
            val: "position",
            fn: 1
        }, {
            val: "scrollTop",
            fn: 1
        }, {
            val: "scrollLeft",
            fn: 1
        }, {
            val: "height",
            fn: 1
        }, {
            val: "width",
            fn: 1
        }, {
            val: "innerHeight",
            fn: 1
        }, {
            val: "innerWidth",
            fn: 1
        }, {
            val: "outerHeight",
            fn: 1
        }, {
            val: "outerWidth",
            fn: 1
        }]
    }, {
        title: "文档处理",
        props: [{
            val: "append",
            fn: 1
        }, {
            val: "appendTo",
            fn: 1
        }, {
            val: "prepend",
            fn: 1
        }, {
            val: "prependTo",
            fn: 1
        }, {
            val: "after",
            fn: 1
        }, {
            val: "before",
            fn: 1
        }, {
            val: "insertAfter",
            fn: 1
        }, {
            val: "insertBefore",
            fn: 1
        }, {
            val: "wrap",
            fn: 1
        }, {
            val: "unwrap",
            fn: 1
        }, {
            val: "wrapAll",
            fn: 1
        }, {
            val: "wrapInner",
            fn: 1
        }, {
            val: "replaceWith",
            fn: 1
        }, {
            val: "replaceAll",
            fn: 1
        }, {
            val: "empty",
            fn: 1
        }, {
            val: "remove",
            fn: 1
        }, {
            val: "detach",
            fn: 1
        }, {
            val: "clone",
            fn: 1
        }]
    }, {
        title: "过滤和筛选",
        props: [{
            val: "eq",
            fn: 1
        }, {
            val: "first",
            fn: 1
        }, {
            val: "last",
            fn: 1
        }, {
            val: "hasClass",
            fn: 1
        }, {
            val: "filter",
            fn: 1
        }, {
            val: "is",
            fn: 1
        }, {
            val: "map",
            fn: 1
        }, {
            val: "has",
            fn: 1
        }, {
            val: "not",
            fn: 1
        }, {
            val: "slice",
            fn: 1
        }]
    }, {
        title: "查找元素",
        props: [{
            val: "children",
            fn: 1
        }, {
            val: "closest",
            fn: 1
        }, {
            val: "find",
            fn: 1
        }, {
            val: "next",
            fn: 1
        }, {
            val: "nextAll",
            fn: 1
        }, {
            val: "nextUntil",
            fn: 1
        }, {
            val: "offsetParent",
            fn: 1
        }, {
            val: "parent",
            fn: 1
        }, {
            val: "parents",
            fn: 1
        }, {
            val: "parentsUntil",
            fn: 1
        }, {
            val: "prev",
            fn: 1
        }, {
            val: "prevAll",
            fn: 1
        }, {
            val: "prevUntil",
            fn: 1
        }, {
            val: "siblings",
            fn: 1
        }]
    }, {
        title: "串联",
        props: [{
            val: "add",
            fn: 1
        }, {
            val: "andSelf",
            fn: 1
        }, {
            val: "contents",
            fn: 1
        }, {
            val: "end",
            fn: 1
        }]
    }, {
        title: "效果",
        props: [{
            val: "show",
            fn: 1
        }, {
            val: "hide",
            fn: 1
        }, {
            val: "toggle",
            fn: 1
        }, {
            val: "slideDown",
            fn: 1
        }, {
            val: "slideUp",
            fn: 1
        }, {
            val: "slideToggle",
            fn: 1
        }, {
            val: "fadeIn",
            fn: 1
        }, {
            val: "fadeOut",
            fn: 1
        }, {
            val: "fadeTo",
            fn: 1
        }, {
            val: "fadeToggle",
            fn: 1
        }, {
            val: "animate",
            fn: 1
        }, {
            val: "stop",
            fn: 1
        }, {
            val: "delay",
            fn: 1
        }, {
            val: "finish",
            fn: 1
        }]
    }, {
        title: "页面载入",
        props: [{
            val: "ready",
            //base代表默认一定会支持的
            base: 1
        }]
    }, {
        title: "事件处理",
        props: [{
            val: "on",
            fn: 1
        }, {
            val: "off",
            fn: 1
        }, {
            val: "bind",
            fn: 1
        }, {
            val: "one",
            fn: 1
        }, {
            val: "trigger",
            fn: 1
        }, {
            val: "triggerHandler",
            fn: 1
        }, {
            val: "unbind",
            fn: 1
        }, {
            val: "live",
            fn: 1
        }, {
            val: "die",
            fn: 1
        }, {
            val: "delegate",
            fn: 1
        }, {
            val: "undelegate",
            fn: 1
        }, {
            val: "hover",
            fn: 1
        }, {
            val: "toggle",
            fn: 1
        }, {
            val: "$.Event"
        }]
    }, {
        title: "事件",
        props: [{
            val: "blur",
            fn: 1
        }, {
            val: "change",
            fn: 1
        }, {
            val: "click",
            fn: 1
        }, {
            val: "dblclick",
            fn: 1
        }, {
            val: "error",
            fn: 1
        }, {
            val: "focus",
            fn: 1
        }, {
            val: "focusin",
            fn: 1
        }, {
            val: "focusout",
            fn: 1
        }, {
            val: "keydown",
            fn: 1
        }, {
            val: "keypress",
            fn: 1
        }, {
            val: "keyup",
            fn: 1
        }, {
            val: "mousedown",
            fn: 1
        }, {
            val: "mouseenter",
            fn: 1
        }, {
            val: "mouseleave",
            fn: 1
        }, {
            val: "mousemove",
            fn: 1
        }, {
            val: "mouseout",
            fn: 1
        }, {
            val: "mouseover",
            fn: 1
        }, {
            val: "mouseup",
            fn: 1
        }, {
            val: "resize",
            fn: 1
        }, {
            val: "scroll",
            fn: 1
        }, {
            val: "select",
            fn: 1
        }, {
            val: "submit",
            fn: 1
        }, {
            val: "unload",
            fn: 1
        }, {
            val: "contextmenu",
            fn: 1
        }]
    }, {
        title: "ajax",
        props: [{
            val: "$.ajax"
        }, {
            val: "load",
            fn: 1
        }, {
            val: "$.get"
        }, {
            val: "$.getJSON"
        }, {
            val: "$.getScript"
        }, {
            val: "$.post"
        }, {
            val: "ajaxComplete",
            fn: 1
        }, {
            val: "ajaxError",
            fn: 1
        }, {
            val: "ajaxSend",
            fn: 1
        }, {
            val: "ajaxStart",
            fn: 1
        }, {
            val: "ajaxStop",
            fn: 1
        }, {
            val: "ajaxSuccess",
            fn: 1
        }, {
            val: "$.ajaxSetup"
        }, {
            val: "$.serialize"
        }, {
            val: "$.serializearray"
        }]
    }, {
        title: "工具",
        props: [{
            val: "$.support"
        }, {
            val: "$.browser"
        }, {
            val: "$.browser.version"
        }, {
            val: "$.boxModel"
        }, {
            val: "$.each"
        }, {
            val: "$.extend"
        }, {
            val: "$.grep"
        }, {
            val: "$.makearray"
        }, {
            val: "$.map"
        }, {
            val: "$.inarray"
        }, {
            val: "$.toarray"
        }, {
            val: "$.merge"
        }, {
            val: "$.unique"
        }, {
            val: "$.parseJSON"
        }, {
            val: "$.noop"
        }, {
            val: "$.proxy"
        }, {
            val: "$.contains"
        }, {
            val: "$.type"
        }, {
            val: "$.isarray"
        }, {
            val: "$.isFunction"
        }, {
            val: "$.isEmptyObject"
        }, {
            val: "$.isPlainObject"
        }, {
            val: "$.isWindow"
        }, {
            val: "$.isNumeric"
        }, {
            val: "$.trim"
        }, {
            val: "$.param"
        }, {
            val: "$.error"
        }, {
            val: "$.proxy"
        }]
    }, {
        title: "Deferred",
        props: [{
            val: "$.Deferred"
        }, {
            val: "notify",
            is: "$.Deferred"
        }, {
            val: "resolve",
            is: "$.Deferred"
        }, {
            val: "reject",
            is: "$.Deferred"
        }, {
            val: "progress",
            is: "$.Deferred"
        }, {
            val: "done",
            is: "$.Deferred"
        }, {
            val: "fail",
            is: "$.Deferred"
        }, {
            val: "always",
            is: "$.Deferred"
        }, {
            val: "state",
            is: "$.Deferred"
        }, {
            val: "promise",
            is: "$.Deferred"
        }]
    }, {
        title: "jquery对象访问",
        props: [{
            val: "each",
            fn: 1
        }, {
            val: "size",
            fn: 1
        }, {
            val: "selector",
            fn: 1
        }, {
            val: "content",
            fn: 1
        }, {
            val: "get",
            fn: 1
        }, {
            val: "index",
            fn: 1
        }]
    }, {
        title: "数据缓存",
        props: [{
            val: "data",
            fn: 1
        }, {
            val: "removeData",
            fn: 1
        }, {
            val: "$.data"
        }]
    }, {
        title: "插件机制",
        props: [{
            val: "$.fn.extend",
        }, {
            val: "$.extend",
        }, {
            val: "$.noConflict",
        }]
    }
    // , {
    //     title: "Deferred",
    //     props: [{
    //         val: "$.Deferred",
    //         $: 1
    //     }, {
    //         val: "$.when",
    //         $: 1
    //     }, {
    //         val: "def.done"
    //     }]
    // }
];