//注册的jquery方法
var jqdatas = [{
    title: "属性操作",
    props: [{
        val: "attr",
        //是在fn上的方法
        fn: 1
    }, {
        val: "removeAttr",
        fn: 1
    }, {
        val: "prop",
        fn: 1
    }, {
        val: "removeProp",
        fn: 1
    }, {
        val: "addClass",
        fn: 1
    }, {
        val: "removeClass",
        fn: 1
    }, {
        val: "toggleClass",
        fn: 1
    }, {
        val: "html",
        fn: 1
    }, {
        val: "text",
        fn: 1
    }, {
        val: "val",
        fn: 1
    }]
}, {
    title: "CSS相关和定位",
    props: [{
        val: "css",
        fn: 1
    }, {
        val: "offset",
        fn: 1
    }, {
        val: "position",
        fn: 1
    }, {
        val: "scrollTop",
        fn: 1
    }, {
        val: "scrollLeft",
        fn: 1
    }, {
        val: "height",
        fn: 1
    }, {
        val: "width",
        fn: 1
    }, {
        val: "innerHeight",
        fn: 1
    }, {
        val: "innerWidth",
        fn: 1
    }, {
        val: "outerHeight",
        fn: 1
    }, {
        val: "outerWidth",
        fn: 1
    }]
}, {
    title: "文档处理",
    props: [{
        val: "append",
        fn: 1
    }, {
        val: "appendTo",
        fn: 1
    }, {
        val: "prepend",
        fn: 1
    }, {
        val: "prependTo",
        fn: 1
    }, {
        val: "after",
        fn: 1
    }, {
        val: "before",
        fn: 1
    }, {
        val: "insertAfter",
        fn: 1
    }, {
        val: "insertBefore",
        fn: 1
    }, {
        val: "wrap",
        fn: 1
    }, {
        val: "unwrap",
        fn: 1
    }, {
        val: "wrapAll",
        fn: 1
    }, {
        val: "wrapInner",
        fn: 1
    }, {
        val: "replaceWith",
        fn: 1
    }, {
        val: "replaceAll",
        fn: 1
    }, {
        val: "empty",
        fn: 1
    }, {
        val: "remove",
        fn: 1
    }, {
        val: "detach",
        fn: 1
    }, {
        val: "clone",
        fn: 1
    }]
}, {
    title: "过滤和筛选",
    props: [{
        val: "eq",
        fn: 1
    }, {
        val: "first",
        fn: 1
    }, {
        val: "last",
        fn: 1
    }, {
        val: "hasClass",
        fn: 1
    }, {
        val: "filter",
        fn: 1
    }, {
        val: "is",
        fn: 1
    }, {
        val: "map",
        fn: 1
    }, {
        val: "has",
        fn: 1
    }, {
        val: "not",
        fn: 1
    }, {
        val: "slice",
        fn: 1
    }]
}, {
    title: "查找元素",
    props: [{
        val: "children",
        fn: 1
    }, {
        val: "closest",
        fn: 1
    }, {
        val: "find",
        fn: 1
    }, {
        val: "next",
        fn: 1
    }, {
        val: "nextAll",
        fn: 1
    }, {
        val: "nextUntil",
        fn: 1
    }, {
        val: "offsetParent",
        fn: 1
    }, {
        val: "parent",
        fn: 1
    }, {
        val: "parents",
        fn: 1
    }, {
        val: "parentsUntil",
        fn: 1
    }, {
        val: "prev",
        fn: 1
    }, {
        val: "prevAll",
        fn: 1
    }, {
        val: "prevUntil",
        fn: 1
    }, {
        val: "siblings",
        fn: 1
    }]
}, {
    title: "串联",
    props: [{
        val: "add",
        fn: 1
    }, {
        val: "andSelf",
        fn: 1
    }, {
        val: "contents",
        fn: 1
    }, {
        val: "end",
        fn: 1
    }]
}, {
    title: "效果",
    props: [{
        val: "show",
        fn: 1
    }, {
        val: "hide",
        fn: 1
    }, {
        val: "toggle",
        fn: 1
    }, {
        val: "slideDown",
        fn: 1
    }, {
        val: "slideUp",
        fn: 1
    }, {
        val: "slideToggle",
        fn: 1
    }, {
        val: "fadeIn",
        fn: 1
    }, {
        val: "fadeOut",
        fn: 1
    }, {
        val: "fadeTo",
        fn: 1
    }, {
        val: "fadeToggle",
        fn: 1
    }, {
        val: "animate",
        fn: 1
    }, {
        val: "stop",
        fn: 1
    }, {
        val: "delay",
        fn: 1
    }, {
        val: "finish",
        fn: 1
    }]
}, {
    title: "页面载入",
    props: [{
        val: "ready",
        fn: 1
    }]
}, {
    title: "事件处理",
    props: [{
        val: "on",
        fn: 1
    }, {
        val: "off",
        fn: 1
    }, {
        val: "bind",
        fn: 1
    }, {
        val: "one",
        fn: 1
    }, {
        val: "trigger",
        fn: 1
    }, {
        val: "triggerHandler",
        fn: 1
    }, {
        val: "unbind",
        fn: 1
    }, {
        val: "live",
        fn: 1
    }, {
        val: "die",
        fn: 1
    }, {
        val: "delegate",
        fn: 1
    }, {
        val: "undelegate",
        fn: 1
    }, {
        val: "hover",
        fn: 1
    }, {
        val: "toggle",
        fn: 1
    }]
}, {
    title: "事件",
    props: [{
        val: "blur",
        fn: 1
    }, {
        val: "change",
        fn: 1
    }, {
        val: "click",
        fn: 1
    }, {
        val: "dblclick",
        fn: 1
    }, {
        val: "error",
        fn: 1
    }, {
        val: "focus",
        fn: 1
    }, {
        val: "focusin",
        fn: 1
    }, {
        val: "focusout",
        fn: 1
    }, {
        val: "keydown",
        fn: 1
    }, {
        val: "keypress",
        fn: 1
    }, {
        val: "keyup",
        fn: 1
    }, {
        val: "mousedown",
        fn: 1
    }, {
        val: "mouseenter",
        fn: 1
    }, {
        val: "mouseleave",
        fn: 1
    }, {
        val: "mousemove",
        fn: 1
    }, {
        val: "mouseout",
        fn: 1
    }, {
        val: "mouseover",
        fn: 1
    }, {
        val: "mouseup",
        fn: 1
    }, {
        val: "resize",
        fn: 1
    }, {
        val: "scroll",
        fn: 1
    }, {
        val: "select",
        fn: 1
    }, {
        val: "submit",
        fn: 1
    }, {
        val: "unload",
        fn: 1
    }]
}, {
    title: "ajax",
    props: [{
        val: "$.ajax",
        $: 1
    }, {
        val: "load",
        fn: 1
    }, {
        val: "$.get",
        $: 1
    }, {
        val: "$.getJSON",
        $: 1
    }, {
        val: "$.getScript",
        $: 1
    }, {
        val: "$.post",
        $: 1
    }, {
        val: "ajaxComplete",
        fn: 1
    }, {
        val: "ajaxError",
        fn: 1
    }, {
        val: "ajaxSend",
        fn: 1
    }, {
        val: "ajaxStart",
        fn: 1
    }, {
        val: "ajaxStop",
        fn: 1
    }, {
        val: "ajaxSuccess",
        fn: 1
    }, {
        val: "$.ajaxSetup",
        $: 1
    }, {
        val: "serialize",
        fn: 1
    }, {
        val: "serializearray",
        fn: 1
    }]
}, {
    title: "工具",
    props: [{
        val: "$.support",
        $: 1
    }, {
        val: "$.browser",
        $: 1
    }, {
        val: "$.browser.version",
        $: 1
    }, {
        val: "$.boxModel",
        $: 1
    }, {
        val: "$.each",
        $: 1
    }, {
        val: "$.extend",
        $: 1
    }, {
        val: "$.grep",
        $: 1
    }, {
        val: "$.makearray",
        $: 1
    }, {
        val: "$.map",
        $: 1
    }, {
        val: "$.inarray",
        $: 1
    }, {
        val: "$.toarray",
        $: 1
    }, {
        val: "$.merge",
        $: 1
    }, {
        val: "$.unique",
        $: 1
    }, {
        val: "$.parseJSON",
        $: 1
    }, {
        val: "$.noop",
        $: 1
    }, {
        val: "$.proxy",
        $: 1
    }, {
        val: "$.contains",
        $: 1
    }, {
        val: "$.type",
        $: 1
    }, {
        val: "$.isarray",
        $: 1
    }, {
        val: "$.isFunction",
        $: 1
    }, {
        val: "$.isEmptyObject",
        $: 1
    }, {
        val: "$.isPlainObject",
        $: 1
    }, {
        val: "$.isWindow",
        $: 1
    }, {
        val: "$.isNumeric",
        $: 1
    }, {
        val: "$.trim",
        $: 1
    }, {
        val: "$.param",
        $: 1
    }, {
        val: "$.error",
        $: 1
    }]
}, {
    title: "jquery对象访问",
    props: [{
        val: "each",
        fn: 1
    }, {
        val: "size",
        fn: 1
    }, {
        val: "selector",
        fn: 1
    }, {
        val: "content",
        fn: 1
    }, {
        val: "get",
        fn: 1
    }, {
        val: "index",
        fn: 1
    }]
}, {
    title: "数据缓存",
    props: [{
        val: "data",
        fn: 1
    }, {
        val: "removeData",
        fn: 1
    }, {
        val: "$.data",
        $: 1
    }]
}, {
    title: "插件机制",
    props: [{
        val: "jQuery.fn.extend",
    }, {
        val: "jQuery.extend",
    }, {
        val: "jQuery.noConflict",
    }]
}];